# Generated by Django 2.2.6 on 2019-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agent_apartment_apartmentpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='picture',
            field=models.ImageField(null=True, upload_to='agents/'),
        ),
    ]
