# Generated by Django 2.2.6 on 2019-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
