# Generated by Django 2.2.6 on 2019-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191018_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
