# Generated by Django 2.2.6 on 2019-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191018_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentpicture',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
