# Generated by Django 2.2.6 on 2019-10-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191018_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentpicture',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_pictures', to='core.Apartment'),
        ),
    ]
